django_celery/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("feedback.urls")),
]

feedback/urls.py
from django.urls import path

from feedback.views import FeedbackFormView, SuccessView, index

app_name = "feedback"

urlpatterns = [
    path("", FeedbackFormView.as_view(), name="feedback"),
    path("success/", SuccessView.as_view(), name="success"),
    path("index/", index, name="index"),  
]

feedback/models.py
from django.db import models

# Create your models here.

class Feedback(models.Model):
    email = models.EmailField(max_length=50)
    message = models.CharField(max_length=200)

    def __str__(self):
        return self.email

feedback/forms.py
from django import forms

from feedback.tasks import send_feedback_email_task

class FeedbackForm(forms.Form):
    email = forms.EmailField(label="Email Address")
    message = forms.CharField(
        label="Message", widget=forms.Textarea(attrs={"rows": 5})
    )
    
    def send_email(self):
        send_feedback_email_task.delay(
            self.cleaned_data["email"],self.cleaned_data["message"]
        ) 
        # Using .delay() we can send a task message quickly to Celery

feedback/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
import os
import logging

from feedback.forms import FeedbackForm


class FeedbackFormView(FormView):
    template_name = "feedback/feedback.html"
    form_class = FeedbackForm
    success_url = "/success/"

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class SuccessView(TemplateView):
    template_name = "feedback/success.html"
    

log = logging.getLogger('log')

def index(request):
    log.info("Message for information")
    log.warning("Message for warning")
    log.error("Message for error")
    log.critical("Message for critical error")
    return render(request, 'feedback/index.html')

feedback/templates/feedback/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/bamboo.css">
    <title>Feedback</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                {% block content %}

                {% endblock content %}
            </div>
            <div class="col-4"></div>
        </div>
    </div>


</body>
</html>

feedback/templates/feedback/feedback.html
{% extends 'feedback/base.html' %}

{% block content %}

    <h1>How are we doing?</h1>
    
    <p>Please send us your feedback.</p>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit"/>
    </form>

    <p class="mt-5">If u don't have any feedback, you can go to <a href="{% url 'feedback:index' %}">Home Page</a></p>

{% endblock content %}

feedback/templates/feedback/index.html
{% extends 'feedback/base.html' %}

{% block content %}

<h1>Hello Guys!</h1>

<p>If you have any feedback, you can <a href="{% url 'feedback:feedback' %}">submit feedback</a> response.</p>

{% endblock content %}

feedback/templates/feedback/success.html
{% extends 'feedback/base.html' %}

{% block content %}

<h1>Thank You!</h1>

<p>Your feedback has been recorded.</p>
<p>If you have more to say, you can <a href="{% url 'feedback:feedback' %}">submit another feedback</a> response.</p>

{% endblock content %}